AnnotationSchema = new SimpleSchema
  "text":
    type: String
    optional: true
  "textOffsets":
    type: [Number]
    optional: true

IncidentReportSchema = new SimpleSchema
  _id:
    type: String
    optional: true
  url:
    type: String
    label: "Source the incident is based on"
  addedByUserName:
    type: String
    optional: true
  addedByUserId:
    type: String
    optional: true
  addedDate:
    type: Date
    optional: true
  locations:
    type: [Object]
    optional: true
    blackbox: true
  'locations.$':
    type: Object
    blackbox: true
  travelRelated:
    type: Boolean
    optional: true
  approximate:
    type: Boolean
    optional: true
  disease:
    type: String
    optional: true
  deleted:
    type: Boolean
    optional: true
  deletedDate:
    type: Date
    optional: true
  accepted:
    type: Boolean
    optional: true
  annotations:
    type: Object
    optional: true
  "annotations.case":
    type: [AnnotationSchema]
    optional: true
  "annotations.date":
    type: [AnnotationSchema]
    optional: true
  "annotations.location":
    type: [AnnotationSchema]
    optional: true
  "annotations.disease":
    type: [AnnotationSchema]
    optional: true
  autogenerated:
    type: Boolean
    optional: true
  ignore:
    type: Boolean
    optional: true
  studySite:
    type: Boolean
    optional: true
  coordinates:
    type: Boolean
    optional: true


module.exports = IncidentReportSchema
